name: Deploy to Hugging Face Space (CD)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy_branch

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "ghoshprithwijit39@gmail.com"
          git config --global user.name "Prithwijit24"

          git clone https://huggingface.co/spaces/Prithwijit24/product_reco_deploy hf-space
          echo "=== BEFORE RSYNC ==="
          ls -la
          
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='README.md' \
            --exclude=src/project_folder/notebooks/healthcare* \
            ./ hf-space/ || true

          echo "=== AFTER RSYNC ==="
          cd hf-space
          ls -la
          
          git add .
          git commit -m "Deploy from GitHub deploy branch" || echo "No changes to deploy"
          git push

