name: Deploy to Hugging Face Space (CD)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v4
        with:
          ref: deploy_branch

      - name: Verify branch
        run: git rev-parse --abbrev-ref HEAD

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_ACCESS_TOKEN }}
        run: |
          git config --global user.email "ghoshprithwijit39@gmail.com"
          git config --global user.name "Prithwijit24"

          git clone https://Prithwijit24:${HF_TOKEN}@huggingface.co/spaces/Prithwijit24/product_reco_deploy hf-space
          
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='README.md' \
            --exclude=src/project_folder/notebooks/healthcare* \
            ./ hf-space/ || true

          cd hf-space
          git add .
          echo "=== git add successful ==="
          git commit -m "Deploy from GitHub deploy branch" || echo "No changes to deploy"
          echo "=== git commit successful ==="
          git push
          echo "=== git push successful ==="

